name: release

on:
  push:
    tags:
      - 'v*'

jobs:

  # Aggregate all the assets and ship a release
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      OLLAMA_SKIP_IMAGE_BUILD: '1'
      PUSH: '1'
    steps:
      - uses: actions/checkout@v4
      - name: Set Version
        shell: bash
        run: |
          echo "VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV
          echo "RELEASE_VERSION=$(echo ${GITHUB_REF_NAME} | cut -f1 -d-)" >> $GITHUB_ENV
      - run: |
          mkdir dist/
          echo "hello world" > dist/payload
      - run: |
          ls -lh dist/
          (cd dist; sha256sum * > sha256sum.txt)
          cat dist/sha256sum.txt
      - name: Create or update Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE: ${{ github.event.issue.html_url }}
        run: |
          if ! gh release view ${{ env.RELEASE_VERSION }} ; then
            gh release create \
              --draft \
              --generate-notes \
              --prerelease \
              --target ${GITHUB_REF_NAME}
          else
            echo "Release ${{ env.RELEASE_VERSION }} already exists"
          fi
          gh release upload ${{ env.RELEASE_VERSION }} dist/* --clober 