name: release

on:
  push:
    tags:
      - 'v*'

jobs:

  # Aggregate all the assets and ship a release
  release:
    runs-on: ubuntu
    permissions:
      contents: write
    env:
      OLLAMA_SKIP_IMAGE_BUILD: '1'
      PUSH: '1'
    steps:
      - uses: actions/checkout@v4
      - name: Set Version
        shell: bash
        run: |
          echo "VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV
          echo "RELEASE_VERSION=$(echo ${GITHUB_REF_NAME} | cut -f1 -d-)" >> $GITHUB_ENV
      - run: |
          mkdir dist/
          echo "hello world" > dist/payload
      - run: |
          ls -lh dist/
          (cd dist; sha256sum * > sha256sum.txt)
          cat dist/sha256sum.txt
      - uses: ncipollo/release-action@v1
        with:
          name: ${{ env.RELEASE_VERSION }}
          allowUpdates: true
          artifacts: 'dist/*'
          draft: true
          prerelease: true
          omitBodyDuringUpdate: true
          generateReleaseNotes: true
          omitDraftDuringUpdate: true
          omitPrereleaseDuringUpdate: true
          replacesArtifacts: true
